# Generated by Django 3.1.1 on 2021-04-17 17:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='user',
            name='passport_id',
            field=models.CharField(max_length=11, verbose_name='პირადი ნომერი'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=30, validators=[django.core.validators.RegexValidator('\\(514|551|555|557|558|559|568|570|571|574|577|579|591|592|593|595|596|597|598|599)\\d{6}')], verbose_name='ტელეფონის ნომერი'),
        ),
    ]
