# Generated by Django 3.1 on 2021-05-07 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20210420_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=30, verbose_name='ტელეფონის ნომერი'),
        ),
    ]
